### ISSUE TITLE
Place the three themes in ~themes~ in a separate repository

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/emacs.d#1]
I think this is helpful for users of these themes to synchronize their themes~

**Comment by DogLooksGood** [comment]
Emm, is there really a user of these themes, except me?

**Comment by KiteAB** [comment]
> Emm, is there really a user of these themes, except me?

For an example, me lol

**Comment by DogLooksGood** [comment]
![image](https://user-images.githubusercontent.com/11796018/104699942-6b0cd200-574e-11eb-99d2-a97dae935019.png)

![image](https://user-images.githubusercontent.com/11796018/104699951-6f38ef80-574e-11eb-921b-5b7573ebda02.png)

![image](https://user-images.githubusercontent.com/11796018/104699958-72cc7680-574e-11eb-9df7-d898e3f3ff9b.png)

(just for screenshots)

I'm putting them in separate repos.

**Comment by DogLooksGood** [comment]
Okay, done.  They are

https://github.com/DogLooksGood/joker-theme

https://github.com/DogLooksGood/printed-theme

https://github.com/DogLooksGood/storybook-theme


But since I'm not focusing on developing themes, I won't spend time to add faces those I don't need or refactoring code. 
I'll only add faces when I need one. 

PR is always welcomed, or you can use the code without any limitation.
